/**
--- Day 7: Laboratories ---

You thank the cephalopods for the help and exit the trash compactor,
finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be
researching teleportation; you can't help but try it for yourself and step
onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors;
the only way out is the teleporter. Unfortunately, the teleporter seems to
be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and
diagnostic equipment lying around. After connecting one of the diagnostic
tools, it helpfully displays error code 0H-N0, which apparently means that
there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A
tachyon beam enters the manifold at the location marked S; tachyon beams
always move downward. Tachyon beams pass freely through empty space (.).
However, if a tachyon beam encounters a splitter (^), the beam is stopped;
instead, a new tachyon beam continues from the immediate left and from the
immediate right of the splitter.

For example:

    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............

In this example, the incoming tachyon beam (|) extends downward from S
until it reaches the first splitter:

    .......S.......
    .......|.......
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............

At that point, the original beam stops, and two new beams are emitted from
the splitter:

    .......S.......
    .......|.......
    ......|^|......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............

Those beams continue downward until they reach more splitters:

    .......S.......
    .......|.......
    ......|^|......
    ......|.|......
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............

At this point, the two splitters create a total of only three tachyon
beams, since they are both dumping tachyons into the same place between
them:

    .......S.......
    .......|.......
    ......|^|......
    ......|.|......
    .....|^|^|.....
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............

This process continues until all of the tachyon beams reach a splitter or
exit the manifold:

    .......S.......
    .......|.......
    ......|^|......
    ......|.|......
    .....|^|^|.....
    .....|.|.|.....
    ....|^|^|^|....
    ....|.|.|.|....
    ...|^|^|||^|...
    ...|.|.|||.|...
    ..|^|^|||^|^|..
    ..|.|.|||.|.|..
    .|^|||^||.||^|.
    .|.|||.||.||.|.
    |^|^|^|^|^|||^|
    |.|.|.|.|.|||.|

To repair the teleporter, you first need to understand the beam-splitting
properties of the tachyon manifold. In this example, a tachyon beam is
split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?

--- Part Two ---

With your analysis of the manifold complete, you begin fixing the
teleporter. However, as you open the side of the teleporter to replace the
broken manifold, you are surprised to discover that it isn't a classical
tachyon manifold - it's a quantum tachyon manifold.

With a quantum tachyon manifold, only a single tachyon particle is sent
through the manifold. A tachyon particle takes both the left and right path
of each splitter encountered.

Since this is impossible, the manual recommends the many-worlds
interpretation of quantum tachyon splitting: each time a particle reaches a
splitter, it's actually time itself which splits. In one timeline, the
particle went left, and in the other timeline, the particle went right.

To fix the manifold, what you really need to know is the number of
timelines active after a single particle completes all of its possible
journeys through the manifold.

In the above example, there are many timelines. For instance, there's the
timeline where the particle always went left:

    .......S.......
    .......|.......
    ......|^.......
    ......|........
    .....|^.^......
    .....|.........
    ....|^.^.^.....
    ....|..........
    ...|^.^...^....
    ...|...........
    ..|^.^...^.^...
    ..|............
    .|^...^.....^..
    .|.............
    |^.^.^.^.^...^.
    |..............

Or, there's the timeline where the particle alternated going left and right
at each splitter:

    .......S.......
    .......|.......
    ......|^.......
    ......|........
    ......^|^......
    .......|.......
    .....^|^.^.....
    ......|........
    ....^.^|..^....
    .......|.......
    ...^.^.|.^.^...
    .......|.......
    ..^...^|....^..
    .......|.......
    .^.^.^|^.^...^.
    ......|........

Or, there's the timeline where the particle ends up at the same point as
the alternating timeline, but takes a totally different path to get there:

    .......S.......
    .......|.......
    ......|^.......
    ......|........
    .....|^.^......
    .....|.........
    ....|^.^.^.....
    ....|..........
    ....^|^...^....
    .....|.........
    ...^.^|..^.^...
    ......|........
    ..^..|^.....^..
    .....|.........
    .^.^.^|^.^...^.
    ......|........

In this example, in total, the particle ends up on 40 different timelines.

Apply the many-worlds interpretation of quantum tachyon splitting to your
manifold diagram. In total, how many different timelines would a single
tachyon particle end up on?
*/
#[cfg(test)]
mod tests {
    use crate::utils::files::read_lines;
    use std::collections::HashMap;
    use std::ops::AddAssign;
    use std::path::Path;
    #[test]
    fn input_example() {
        let input = r#".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."#;

        let lines = input.split("\n").into_iter().map(str::to_string);

        let split = count_timeline(lines.into_iter());

        assert_eq!(split.0, 21);
        assert_eq!(split.1, 40);
    }

    fn count_timeline<T>(lines: T) -> (usize, usize)
    where
        T: Iterator<Item = String>,
    {
        let mut split = 0;
        let mut beams: HashMap<usize, usize> = HashMap::new();
        for (n, line) in lines.enumerate() {
            if n == 0 {
                match line.find("S") {
                    None => {
                        println!("Cannot find starting position in input");
                    }
                    Some(i) => {
                        beams.insert(i, 1);
                    }
                }
            } else {
                for (i, c) in line.chars().enumerate() {
                    if c == '^' {
                        match beams.remove(&i) {
                            None => {}
                            Some(value) => {
                                split += 1;
                                beams.entry(i + 1).or_insert(0).add_assign(value);
                                beams.entry(i - 1).or_insert(0).add_assign(value);
                            }
                        }
                    }
                }
                println!("Beams: {:?}", beams);
            }
        }
        let timeline = beams.values().into_iter().sum();
        (split, timeline)
    }

    #[test]
    fn input_part_1() {
        let path = Path::new("data/day07.txt");

        let lines = read_lines(path);

        let split = count_timeline(lines.into_iter());

        assert_eq!(split.0, 1587);
    }

    #[test]
    fn input_part_2() {
        let path = Path::new("data/day07.txt");

        let lines = read_lines(path);

        let split = count_timeline(lines.into_iter());

        assert_eq!(split.1, 5748679033029);
    }
}
